# Generated by Django 2.2.6 on 2020-10-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.CharField(choices=[('qd', '前端开发'), ('hd', '后端开发')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_need',
            field=models.CharField(max_length=100, null=True, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_notice',
            field=models.CharField(max_length=200, null=True, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='desc',
            field=models.CharField(max_length=200, null=True, verbose_name='课程简介'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='detail',
            field=models.TextField(null=True, verbose_name='课程详情'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(max_length=20, null=True, upload_to='course/', verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='orginfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgInfo', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='teacher_tell',
            field=models.CharField(max_length=200, null=True, verbose_name='教学指导'),
        ),
    ]
