# Generated by Django 2.2.6 on 2020-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20201007_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to='course/', verbose_name='课程封面'),
        ),
    ]
