# Generated by Django 2.2.6 on 2020-10-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_start',
            new_name='is_status',
        ),
    ]
