# Generated by Django 2.2.6 on 2020-10-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAks',
            new_name='UserAsk',
        ),
    ]
