# Generated by Django 2.2.6 on 2020-10-16 18:27

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20201007_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginfo',
            old_name='cityyinfo',
            new_name='cityinfo',
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='机构详情'),
        ),
    ]
